### ISSUE TITLE
Issues when I paste an item into the WorkSpace of the project

### ISSUE THREAD

**Issue by Alexisvt** [alm-tools/alm#110]
Hi @basarat Is it normal that alm tool doesn't recognize the files when they are copied into the workspace? 
The workaround is to restart alm tool and then alm tool sees the new added files!

**Comment by basarat** [comment]
> doesn't recognize the files when they are copied into the workspace?

You add new files in the file system and they don't show up in the tree view? They definitely should. 

In fact we do not tell any code about new files *we add*. The tree view backend actually just picks them up as they show on the file system (so that it can pickup the files no matter who adds them ... us or something external). 

More info please! :rose:

**Comment by Alexisvt** [comment]
Good morning @basarat! I don't know what happened yesterday because today I can't reproduce the error again! I did some test and everything works fine!
