### ISSUE TITLE
Vscode monaco

### ISSUE THREAD

**Issue by Brakkar** [alm-tools/alm#137]
Hello,
Congratulations on the excellent work.

Will this be ported to vscode as an extension, or as a monaco stand alone ?
Any release date estimation ?

**Comment by basarat** [comment]
> Will this be ported to vscode as an extension

I don't know yet. There are a lot of opinions here that are my own and I haven't run them by everyone. Some of them contradict with VSCode defaults. I love the vscode team but just wanted complete creative freedom :rose: 

>  or as a monaco stand alone

Suspect you mean electron standalone. Please see https://github.com/alm-tools/alm/issues/132

> Any release date estimation ?

Already released on npm `npm install alm -g` :rose:

**Comment by Brakkar** [comment]
> Already released on npm npm install alm -g 🌹

I meant as a vscode extension.
problem on mac is that I don't like to use chrome because of poor performance of the browser and chrome helper constantly consuming high cpu

**Comment by basarat** [comment]
> problem on mac is that I don't like to use chrome because of poor performance of the browser a

VSCode uses chrome as well so it will perform the same.

> I meant as a vscode extension.

Thanks for clarifying. I haven't decided any integrations yet as it does what I want it to and its easier to maintain as its own thing (instead of a plugin for a *particular* IDE) More : https://basarat.gitbooks.io/alm/content/contributing/why.html :rose:
