### ISSUE TITLE
Basic syntax highlighting for other languages

### ISSUE THREAD

**Issue by niieani** [alm-tools/alm#185]
Build systems often contain code in other languages than TypeScript or even JavaScript. It would be useful for `alm` to include rudimentary syntax highlighting support for those other languages that might commonly be mixed. I think most important languages used alongside npm / TypeScript contexts would be:

- [ ] bash
- [ ] python
- [ ] Dockerfile / docker-compose.yml
- [ ] gitignore / npmignore / editorconfig
- [ ] [maybe] Go
- [ ] ...others?

I see XML and Markdown are already supported, but it would be extra nice if ticking to-do's were possible, like in GitHub or iA Writer (lists with items starting with: `[ ]`).

This would also make alm a great overall remote editor for server side changes to code in general (not necessarily TypeScript) - you'd spin up an alm instance instead of nano/mcedit/vim/micro and get the real deal and comfort of a graphical editor.

**Comment by basarat** [comment]
We used to use CodeMirror that has an amazing list : http://codemirror.net/mode/

We since moved to monaco due to simplicity of sharing knowledge / code with Microsoft. So now we are limited to whatever https://github.com/Microsoft/monaco-languages supports. The list is quite small but what ever gets there will definitely show up here. The goal till now is *just TypeScript* (and JavaScript) but be amazing there. Closing as it needs external / upstream work : https://github.com/Microsoft/monaco-editor/issues :rose:
