### ISSUE TITLE
File tree font size is too small

### ISSUE THREAD

**Issue by emzero** [alm-tools/alm#214]
I find that the font size in the file tree view is too small for me to read. I know I could use Chrome's zoom but that makes everything larger and I just want to increase the size of the file tree area.

Is there a way to do that? If not, would you consider adding a setting for it?

Thank you!

**Comment by basarat** [comment]
> Is there a way to do that? If not, would you consider adding a setting for it?

Not at the moment. Sorry about that :rose:

**Comment by davideicardi** [comment]
Also on my browser (latest Chrome on Ubuntu 16)  the tree view seems to be very small.
![image](https://cloud.githubusercontent.com/assets/852570/23324337/74964020-faed-11e6-97a6-94a76ae4eab3.png)

On your documentation screenshot seems to be just fine... It is an UI problem or is this by design? Maybe I just too old :smile:

**Comment by hoegge** [comment]
Just a vote for this -

**Comment by hoegge** [comment]
Please make this a priority. It is very hard to see the tree and object browser if you use a font that is not "magnaprint" in the editor. It is half the size of the editor font.

<img width="489" alt="screen shot 2017-08-07 at 23 07 02" src="https://user-images.githubusercontent.com/15846310/29045814-2ca2fcd2-7bc5-11e7-8d44-327bb6acbb73.png">
