### ISSUE TITLE
BOM syntax-highlighting issue

### ISSUE THREAD

**Issue by nycdotnet** [alm-tools/alm#227]
When opening `tests/tests.ts` from https://github.com/typeStrong/csproj2ts , the syntax highlighting is off by one character.  I believe this is due to the presence of a UTF-8 BOM.

Also of note, is that changing the encoding in another editor (to remove the BOM) and then re-opening the file in alm does not resolve the issue.  I had to quit ALM and then go back in for it to show the syntax highlighting properly.

I would like to take a crack at fixing this myself.

**Comment by basarat** [comment]
Just the fact that you even used it makes my day :rose: :heart: :) 

Tips on the fix: 

* All TypeScript code highlighting is in the front end. How the typescript code highlighting works is documented here : https://basarat.gitbooks.io/alm/content/contributing/syntax.html
* You can probably ignore this but in case you were wondering : The backend keeps a list (`FileModelCache` https://github.com/alm-tools/alm/blob/c93f4e572cf700d2afbb763e2f50ae18498f4de1/src/server/disk/fileModelCache.ts < will not need any changing) of opened files as a very simple `FileModel` (https://github.com/alm-tools/alm/blob/c93f4e572cf700d2afbb763e2f50ae18498f4de1/src/server/disk/fileModel.ts might need changing ... but probably not). Right now the only info about the *nature* of the file it has is the newlines and even there it is won over by whatever is in the `.editorconfig`. I'm not too worried about making it high quality with bells and whistles of world class file handling because the focus has always been providing a great *TypeScript* experience :)

Best of luck and I am here for any help that you might need 👍.

**Comment by nycdotnet** [comment]
Thanks. I notice you are dangerously close to 1000 stars.

**Comment by basarat** [comment]
I looked into this as I felt like helping you :rose:. The following are some notes: 

* The TypeScript's `getEncodedSyntacticClassifications` doesn't support BOM in that it ignores its length when doing tokenization. So we need to track the bom in `classifierCache` < that fixes it for the first load
* That said monaco in itself doesn't handle BOM very well in that it allows the user to *move* it if the user edits from the start of the file as seen in the image below (so I still need to figure out fixing that): 

![editingtopoffile](https://cloud.githubusercontent.com/assets/874898/19217622/8596aeca-8e2b-11e6-9132-d3b590f12137.gif)

Note : I did consider handling BOM in the fileModel and silintly noting it down but not telling the frontend, but that would break any deltas or workers reading the file contents (e.g. tslint) etc so will continue down the path of making the frontend handle BOM properly :rose:

**Comment by basarat** [comment]
I've opened a PR : https://github.com/alm-tools/alm/pull/234 with a partial fix :heart:

**Comment by basarat** [comment]
So the bom syntax highlighting (TypeScript issue) is fixed (in our classiferCache)

However, I cannot think of a way to patch the *moving BOM* issue easily without actually fixing it in monaco itself :-/

**Comment by nycdotnet** [comment]
Thanks for doing this.  I certainly would have gone the ignorant route and just lied to the UI, but I suppose you're right - this could mess up other stuff.  You have cured me of the desire to try to fix this.  I am surprised this didn't come up earlier for the Monaco team considering Microsoft and Visual Studio in particular loves the BOM so much.

I'm working on (yet another) rewrite for grunt-ts to make it tsconfig.json-first (even using temporary tsconfigs instead of using command-line switches) and removing all of the bolt-on stuff in the core package.  My intent is to provide a middle-ware/plugin solution to replace that functionality.  For your amusement: https://github.com/nycdotnet/grunt-ts-new

**Comment by basarat** [comment]
> I am surprised this didn't come up earlier for the Monaco team considering Microsoft and Visual Studio in particular loves the BOM so much.

`monaco` is a bit *bolted on* out of vscode. The vscode TextModel does all the lieing needed.

**Comment by basarat** [comment]
In the off chance that the user edits the first line of a file that has the bom ... it will move. Closing as *syntax* highlighting is fixed and 🙏 ing that the other issue will sort itself out eventually.

**Comment by nycdotnet** [comment]
Thanks man.  :-)
