### ISSUE TITLE
file watcher locks directories on windows

### ISSUE THREAD

**Issue by wizzard0** [alm-tools/alm#261]
they become undeletable

**Comment by basarat** [comment]
> locks directories on windows

Highly probable. That said, I haven't had trouble renaming files / folders *using alm tree view*. A repro would help with investigation :rose: 

Will most likely not lead to a satisfactory solution, but I think its not the file watcher and something else like the tsconfig handler `activeProjectConfig.ts` or something. Because if it was the file watcher everyone would experience it instead of just some edge case. 

PS: Thanks for giving it a go :heart:

**Comment by wizzard0** [comment]
1) it's the file watcher, because killing just that node process helps.
2) tsserver from VS2015 preview 5 and from sublime dont exhibit such behavior
alm 2.5.2

**Comment by basarat** [comment]
Closing as: 

* sporadic (I haven't experienced it myself)
* A hundred reasons why files get locked on windows. The thing that should be preserved is that the file tree represents the true nature of the disk contents e.g. if a file fails to delete it continues to show it ... and that already happens.
