### ISSUE TITLE
peer dep missing: typescript

### ISSUE THREAD

**Issue by tkisme** [alm-tools/alm#317]
npm install -g alm
```
npm WARN tslint@3.15.1 requires a peer of typescript@>=1.7.3 but none was installed.
```

then 

npm ls -g --depth 0
```
/usr/local/lib
├── alm@2.6.0
├── angular-cli@1.0.0-beta.21
├── bower@1.8.0
├── cordova@6.4.0
├── express-generator@4.14.0
├── gulp@3.9.1
├── ionic@2.1.13
├── ios-deploy@1.9.0
├── ios-sim@5.0.12
├── node-gyp@3.4.0
├── node-pre-gyp@0.6.32
├── npm@4.0.2
└── tslint@4.0.2

npm ERR! peer dep missing: typescript@>=1.7.3, required by tslint@3.15.1
```

**Comment by tkisme** [comment]
I think package is okay. It should be npm troubles.I post here if someone care

**Comment by basarat** [comment]
Yup, it works fine without it. Tslint support is not a first class priority for now.

**Comment by basarat** [comment]
I've updated tslint to latest and we still have that error: 

![image](https://cloud.githubusercontent.com/assets/874898/21488456/f8527b24-cc33-11e6-9d89-111cd3935d2d.png)

This is because we ship with (and support!) TypeScript Nightly. This works okay when tslint does a `require('typescript')`, just that npm install gives this warning. So you can safely ignore :rose:
