### ISSUE TITLE
Some notes

### ISSUE THREAD

**Issue by tomitrescak** [alm-tools/alm#66]
@basarat kudos on this new stack, from the first try it looks good and I hope to find some more time to play with it soon. From what I can see the most pending issues for me before I could adopt this as my first choice is:

1. Missing "Build" option
2. Integration of testing tools such as Wallaby.js

Also I've found out that this is suffering from the same issue as the atom-plugin and that it just never ignores the "node_modules". Asa result indexing and reindexing of the project folder takes significant amount of time.

This is except from my tsconfig.json

```
  "filesGlob": [
    "!./node_modules/**",
    "**/*.ts",
    "**/*.tsx",
  ],
  "exclude": [
    "node_modules",
    "./**/node_modules"
  ],
```

**Comment by basarat** [comment]
> Missing "Build" option

You shouldn't need it! If a file changes its compiled (even if it is done by an external editor). Unless you are using `outFile` / `out`? 

> Integration of testing tools such as Wallaby.js

Yes I wouldn't call this the best unless code coverage + live testing is offered. What framework are you using with wallaby? `mocha`/`jasmine`/ something else

> Asa result indexing and reindexing of the project folder takes significant amount of time.

That should work fine. I'll do testing on OSS projects in a few months and that will highlight usage issues. This project isn't **ready** as in not to the level I want. So thanks for giving it a go! :rose: 

My most urgent task is to get a nice [multi pane layout going](https://twitter.com/basarat/status/725073175260880896) (already have multi window / monitor! https://basarat.gitbooks.io/alm/content/features/tabs.html) I'll leave this open till I'v either created separate issues / fixed a few.

**Comment by basarat** [comment]
Mutli pane layout is released! https://basarat.gitbooks.io/alm/content/features/tabs.html so coming back to this.

# Testing 

I've created a new issue for the desire of `integrated testing` : https://github.com/alm-tools/alm/issues/69 so closing this one.

# Build

Also added a progress bar that shows the progress of `emit` whenever we do a full build: 

![build](https://cloud.githubusercontent.com/assets/874898/15095953/133c1762-1526-11e6-9d8d-acc2a4f4c7ad.gif)

I also added a `sync` command (mapped to `f6`, and ofcourse you can find it in the command search) so you can trigger a build whenever you want. You shouldn't need to do this manually anymore unlike atom-typescript, but I added it since you asked and well things can still go bad and I'd rather let you have this power :zap:  https://basarat.gitbooks.io/alm/content/features/typescript.html#sync 


# Performance

Can you share the project that is being slow for you. This project shouldn't need to reevaluate `tsconfig` as much as atom so there shouldn't be siginificant delays. I've pushed some stronger validations around tsconfig so that might have fixed the issues for you ([some boring contributing docs](https://basarat.gitbooks.io/alm/content/contributing/tsconfig.html)) :rose:
