### ISSUE TITLE
Switch to typings included in the golden-layout package

### ISSUE THREAD

**Issue by stephenjelfs** [alm-tools/alm#70]
The complete typings should be available in the golden-layout package soon:
https://github.com/deepstreamIO/golden-layout/pull/103

@basarat The Header interface has addTab and removeTab methods. Maybe these are easier to work with than appendChild/removeChild?

**Comment by basarat** [comment]
Thanks :rose:

> The complete typings should be available in the golden-layout package soon

Will check when available. However `export =` style modules don't lend them selves to easy *interface* usage (e.g. I need the `Config` interface) so I will end up copying again. Its not bad since typings are just docs and its okay to add custom docs for your own project requirements. 



> The Header interface has addTab and removeTab methods. Maybe these are easier to work with than appendChild/removeChild

Maybe. Will explore in some other time. But the current layout was a *pain* to get working (search for `setTimeout` in `appTabsContainer.tsx`). So since it works I don't plan to touch it for a while. I do go through times when new features are bubbling through my grey matter and then take the time to clean up stuff that is in my head about the old code that is bugging me and being a potential blocker for other developers (hence we have these docs https://basarat.gitbooks.io/alm/content/contributing/) :rose:

**Comment by stephenjelfs** [comment]
@basarat FYI After seeing the _pain_ you went through getting golden-layout to work, I decided to check out @phosphorjs -- so far it seems much easier to work with, and it's written in TypeScript too :smile:

**Comment by basarat** [comment]
> I decided to check out @phosphorjs

I did that *first*. https://github.com/alm-tools/alm/pull/67 the first few commits are with PhosphorJS. The main blocker was that it didn't have drag and drop *tab* reordering. Probably should have asked as a feature, but other people were also hyped about golden layout so considered worth exploring 

Also a key difficulty I had was the component heirarchy : *react component to imperative layout to react component*. Now that that work is done I feel more comfortable replacing golden layout with anything but else if need be. It hasn't leaked out of `appTabsContainer.tsx` :rose:
